services:
  hearbe-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hearbe-backend
    ports:
      - "${HOST_PORT}:8080" # 변수화 (prod: 80, dev: 8080)
    env_file:
      - .env
    environment:
<<<<<<< Updated upstream
      # Docker 내부에서는 컨테이너 이름으로 접속
      - SPRING_DATASOURCE_URL=jdbc:mysql://hearbe-mariadb:3306/hearbe?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATA_REDIS_HOST=hearbe-redis
=======
      - SPRING_PROFILES_ACTIVE=${APP_PROFILE} # dev 또는 prod 주입
      - SPRING_DATASOURCE_URL=jdbc:mysql://hearbe-mariadb:3306/hearbe?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATA_REDIS_HOST=hearbe-redis
      - LOG_PATH=/logs # 컨테이너 내부 로그 경로
    volumes:
      - ${HOST_LOG_PATH}:/logs # 호스트와 로그 폴더 연결
>>>>>>> Stashed changes
    depends_on:
      - hearbe-mariadb
      - hearbe-redis
  hearbe-mariadb:
    image: mariadb:latest
    container_name: hearbe-mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  hearbe-phpmyadmin:
    image: phpmyadmin:latest
    container_name: hearbe-phpmyadmin
    env_file:
      - .env
    ports:
      - "8108:80" # phpMyAdmin에 접속하는 포트
    depends_on:
      - hearbe-mariadb
  hearbe-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: hearbe-redis
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
  hearbe-peer:
    image: peerjs/peerjs-server
    container_name: hearbe-peer
    ports:
      - "9000:9000"
    restart: always
    command: [ "--port", "9000", "--path", "/hearbe-peer" ]
volumes:
  mariadb_data:
  redis_data:
