services:
  mariadb:
    image: mariadb:latest
    container_name: hearbe-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: here0119
      MYSQL_DATABASE: hearbe
      MYSQL_USER: hearbe
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: hearbe-phpmyadmin
    environment:
      PMA_HOST: mariadb # 기본적으로 mariadb에 연결
      PMA_USER: hearbe
      PMA_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: here0119 # MariaDB root 비밀번호
    ports:
      - "9008:80" # phpMyAdmin에 접속하는 포트
    depends_on:
      - mariadb
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: hearbe-redis
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "1234"]
volumes:
  mariadb_data:
  redis_data:
