spring.application.name=Backend

# Server Configuration
server.port=8080

# Database Configuration
# Connects to MariaDB container 'herewego' on port 3307
spring.datasource.url=${env:DB_URL}
spring.datasource.username=${env:DB_USERNAME}
spring.datasource.password=${env:DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Redis Configuration
# Connects to Redis container 'herewepick-redis' on port 6379
spring.data.redis.host=${env:REDIS_HOST}
spring.data.redis.port=${env:REDIS_PORT}
spring.data.redis.password=${env:REDIS_PASSWORD}

# JWT Configuration
# 256-bit secure random key generated on 2026-01-27
jwt.secret=${env:JWT_SECRET}
jwt.expiration=${env:JWT_EXPIRATION}

# Encryption Configuration (32 bytes)
encryption.secret-key=${env:ENCRYPTION_SECRET_KEY}
